import { Dimensions, ScrollView, StyleSheet, View } from 'react-native'
import React, { useContext, useEffect, useState } from 'react'
import TitleBar from '../components/TitleBar'
import TimeSeries5min from '../assets/TimeSeries5min'
import Loader from '../components/Loader'
import StockDesc from '../components/StockDesc'
import { AppContext } from '../utils/AppContext'
import Chart from '../components/Chart'
import moment from 'moment'
import StocksHeader from '../components/StocksHeader'
import GETRequest from '../utils/Apis'



const Details = ({navigation, route}) => {

    //State variables
    const [sampleData, setSampleData] = useState([])
    const [stock, setStock] = useState({})

    //Data configured from route
    const item = route?.params?.item
    const tab = route?.params?.tab
    const percent = Number(item?.change_percentage.substring(0, item?.change_percentage.length - 1))

    // Fetch Data from Context
    const {loading, setLoading} = useContext(AppContext)

    const stockParams = [
        { id: 1, name: "Market Cap", value: `$${(stock?.MarketCapitalization/1e10).toFixed(2)}T`},
        { id: 2, name: "P/E Ratio", value: stock?.PERatio},
        { id: 3, name: "Beta", value: stock?.Beta},
        { id: 4, name: "Dividend Yield", value: stock?.DividendYield+"%"},
        { id: 5, name: "Profit Margin", value: stock?.ProfitMargin},
    ]
    const data = {
        "Symbol": "IBM",
        "AssetType": "Common Stock",
        "Name": "International Business Machines",
        "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        "CIK": "51143",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "TECHNOLOGY",
        "Industry": "COMPUTER & OFFICE EQUIPMENT",
        "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
        "FiscalYearEnd": "December",
        "LatestQuarter": "2024-03-31",
        "MarketCapitalization": "156943335000",
        "EBITDA": "14380000000",
        "PERatio": "19.37",
        "PEGRatio": "4.2",
        "BookValue": "25.32",
        "DividendPerShare": "6.64",
        "DividendYield": "0.0391",
        "EPS": "8.82",
        "RevenuePerShareTTM": "67.94",
        "ProfitMargin": "0.132",
        "OperatingMarginTTM": "0.102",
        "ReturnOnAssetsTTM": "0.0458",
        "ReturnOnEquityTTM": "0.362",
        "RevenueTTM": "62068998000",
        "GrossProfitTTM": "32688000000",
        "DilutedEPSTTM": "8.82",
        "QuarterlyEarningsGrowthYOY": "0.701",
        "QuarterlyRevenueGrowthYOY": "0.015",
        "AnalystTargetPrice": "181.05",
        "AnalystRatingStrongBuy": "4",
        "AnalystRatingBuy": "5",
        "AnalystRatingHold": "9",
        "AnalystRatingSell": "3",
        "AnalystRatingStrongSell": "0",
        "TrailingPE": "19.37",
        "ForwardPE": "18.12",
        "PriceToSalesRatioTTM": "2.701",
        "PriceToBookRatio": "7.42",
        "EVToRevenue": "3.453",
        "EVToEBITDA": "14.54",
        "Beta": "0.718",
        "52WeekHigh": "197.22",
        "52WeekLow": "126.18",
        "50DayMovingAverage": "170.57",
        "200DayMovingAverage": "167.29",
        "SharesOutstanding": "918603000",
        "DividendDate": "2024-06-10",
        "ExDividendDate": "2024-05-09"
    }
    
    const uri = `https://picsum.photos/200`
    const screenWidth = Dimensions.get('window').width

    const getSampleData = async ()=>{
        try{
            const timeSeries = TimeSeries5min[`Time Series (5min)`]
            const outputData = {}
            
            for (const timestamp in timeSeries) {
                const k = Number(moment(timestamp).format('X'))
                // console.log(typeof(k), k);
                outputData[k] = {
                    "4. close": Number(timeSeries[timestamp]["4. close"])
                };
            }
            

            fetchSampleData().then((data)=>{
                setSampleData(data)
            })
            // fetchLabelData().then((data) => {
            //     setLabels(data);
            //   });
            //   fetchStockData().then((data)=>{
            //     setStockClose(data)
            //   })

              function fetchSampleData() {
                return new Promise((resolve) => {
                  setTimeout(() => {
                    // resolve(Object.entries(outputData).map(([x, { "4. close": y }]) => ({ x : Number(x), y })));
                    resolve(Object.entries(outputData).map(([x, { "4. close": y }]) => ({ y })));
                  }, 1000);
                });
              }
            // function fetchLabelData() {
            //     return new Promise((resolve) => {
            //       setTimeout(() => {
            //         resolve(Object.keys(outputData).reverse());
            //       }, 2000);
            //     });
            //   }
            //   function fetchStockData() {
            //     return new Promise((resolve) => {
            //       setTimeout(() => {
            //         resolve(labels?.map(label => parseFloat(outputData[label]["4. close"])));
            //       }, 2000);
            //     });
            //   }
        }
        catch(e){
            console.error("Error getSampleData", e);
        }
    }
    


    useEffect(()=>{
        setLoading(true)
        setStock(data)
        getSampleData()
        GETRequest("detail", "function=OVERVIEW&symbol=IBM")

        setTimeout(()=>setLoading(false),2000)
    },[])

    

    
    const chartConfig = {
        backgroundGradientFrom: "#FFFFFF",
        backgroundGradientTo: "#FFFFFF",
        color: (opacity = 1) => `rgba(26, 255, 146, ${opacity})`,
        strokeWidth: 2,
        barPercentage: 0.5,
        useShadowColorFromDataset: false 
    };


    

    
        return (
            loading ? <Loader/> :

            <ScrollView style={{backgroundColor: "#FFFFFF"}}>
                <TitleBar navigation={navigation} screen="Details"/>
    
                <StocksHeader stock={stock} item={item} tab={tab} percent={percent} />
                

                <View style={styles.container}>
                    {
                        sampleData.length > 0 &&
                        <Chart sampleData={sampleData} />
                    }
                </View>
    
                <StockDesc stock={stock} stockParams={stockParams} />
            </ScrollView>
        )
}

export default Details

const styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#fff',
      }
})