import { Dimensions, Image, StyleSheet, Text, View } from 'react-native'
import React, { useEffect, useState } from 'react'
import TitleBar from '../components/TitleBar'
import { LineChart } from 'react-native-chart-kit'

const Details = ({navigation, route}) => {
    const data = {
        "Symbol": "IBM",
        "AssetType": "Common Stock",
        "Name": "International Business Machines",
        "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        "CIK": "51143",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "TECHNOLOGY",
        "Industry": "COMPUTER & OFFICE EQUIPMENT",
        "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
        "FiscalYearEnd": "December",
        "LatestQuarter": "2024-03-31",
        "MarketCapitalization": "156943335000",
        "EBITDA": "14380000000",
        "PERatio": "19.37",
        "PEGRatio": "4.2",
        "BookValue": "25.32",
        "DividendPerShare": "6.64",
        "DividendYield": "0.0391",
        "EPS": "8.82",
        "RevenuePerShareTTM": "67.94",
        "ProfitMargin": "0.132",
        "OperatingMarginTTM": "0.102",
        "ReturnOnAssetsTTM": "0.0458",
        "ReturnOnEquityTTM": "0.362",
        "RevenueTTM": "62068998000",
        "GrossProfitTTM": "32688000000",
        "DilutedEPSTTM": "8.82",
        "QuarterlyEarningsGrowthYOY": "0.701",
        "QuarterlyRevenueGrowthYOY": "0.015",
        "AnalystTargetPrice": "181.05",
        "AnalystRatingStrongBuy": "4",
        "AnalystRatingBuy": "5",
        "AnalystRatingHold": "9",
        "AnalystRatingSell": "3",
        "AnalystRatingStrongSell": "0",
        "TrailingPE": "19.37",
        "ForwardPE": "18.12",
        "PriceToSalesRatioTTM": "2.701",
        "PriceToBookRatio": "7.42",
        "EVToRevenue": "3.453",
        "EVToEBITDA": "14.54",
        "Beta": "0.718",
        "52WeekHigh": "197.22",
        "52WeekLow": "126.18",
        "50DayMovingAverage": "170.57",
        "200DayMovingAverage": "167.29",
        "SharesOutstanding": "918603000",
        "DividendDate": "2024-06-10",
        "ExDividendDate": "2024-05-09"
    }
    const chartData = {
        labels: ["January", "February", "March", "April", "May", "June"],
        datasets: [
          {
            data: [20, 45, 28, 80, 99, 43],
            color: (opacity = 1) => `rgba(134, 65, 244, ${opacity})`, // optional
            strokeWidth: 2 // optional
          }
        ],
        legend: ["Rainy Days"] // optional
      };
    const chartConfig = {
    backgroundGradientFrom: "#1E2923",
    backgroundGradientFromOpacity: 0,
    backgroundGradientTo: "#08130D",
    backgroundGradientToOpacity: 0.5,
    color: (opacity = 1) => `rgba(26, 255, 146, ${opacity})`,
    strokeWidth: 2, // optional, default 3
    barPercentage: 0.5,
    useShadowColorFromDataset: false // optional
    };
    const uri = `https://picsum.photos/200`
    const screenWidth = Dimensions.get('window').width
    
    const [stock, setStock] = useState({})
    useEffect(()=>{
        setStock(data)
    },[])
    const stockParams = [
        { id: 1, name: "Market Cap", value: `$${(stock?.MarketCapitalization/1e10).toFixed(2)}T`},
        { id: 2, name: "P/E Ratio", value: stock?.PERatio},
        { id: 3, name: "Beta", value: stock?.Beta},
        { id: 4, name: "Dividend Yield", value: stock?.DividendYield+"%"},
        { id: 5, name: "Profit Margin", value: stock?.ProfitMargin},
    ]
    return (
        <View>
            <TitleBar navigation={navigation} screen="Details Screen"/>

            <View style={{flexDirection: "row", justifyContent: "space-between", paddingRight: 10}}>
                <View style={{flexDirection: "row"}}>
                    <Image source={{uri : uri}} style={styles.image}/>
                    <View>
                        <Text>{stock?.Name}</Text>
                        <View style={{flexDirection: "row"}}>
                            <Text>{stock?.Symbol}, </Text>
                            <Text>{stock?.AssetType}</Text>
                        </View>
                        <Text>{stock?.Exchange}</Text>
                    </View>
                </View>
                <View>
                    <Text>  Curr val</Text>
                    <Text>  Prof</Text>
                </View>

            </View>

            {/* Chart */}
            <LineChart
                data={chartData}
                width={screenWidth}
                height={220}
                chartConfig={chartConfig}
            />

            <View>
            <Text>  About {stock?.Name}</Text>
            <Text>{stock?.Description}</Text>
            <View style={{flexDirection: "row"}}>
                <View>
                    <Text>Industry : </Text>
                </View>
                <View>
                    <Text>Sector : </Text>
                </View>
            </View>
            <View  style={{flexDirection: "row", justifyContent: "space-around"}}>
                {
                    stockParams?.map((ele)=>{
                        return (
                            <View key={ele?.id}>
                                <Text>{ele?.name}</Text>
                                <Text style={{fontWeight: "600"}}>{ele?.value}</Text>
                            </View>

                        )
                    })
                }
            </View>

            </View>
        </View>
    )
}

export default Details

const styles = StyleSheet.create({
    image: {
        width: 60,
        height: 60,
        borderColor: 'lightgray',
        borderWidth: 2,
        borderRadius: 30,
        marginHorizontal: 6
      },
})