import { Dimensions, Image, ScrollView, StyleSheet, Text, View } from 'react-native'
import React, { useContext, useEffect, useState } from 'react'
import TitleBar from '../components/TitleBar'
import { LineChart } from 'react-native-chart-kit'
import TimeSeries5min from '../assets/TimeSeries5min'
import Loader from '../components/Loader'
import StockDesc from '../components/StockDesc'
import { AppContext } from '../utils/AppContext'
import Chart from '../components/Chart'
import moment from 'moment'

// Text.defaultProps.style = { color: 'black' };


const Details = ({navigation, route}) => {


    const [stockDates, setStockDates] = useState([])
    const [closingVals, setClosingVals] = useState([]);
    const [sampleData, setSampleData] = useState([])
    const [labels, setLabels] = useState([]);
    const [stockClose, setStockClose] = useState([])
    const [chartData, setChartData] = useState({})
    // const [loading, setLoading] = useState(false)

    const {loading, setLoading} = useContext(AppContext)

    const data = {
        "Symbol": "IBM",
        "AssetType": "Common Stock",
        "Name": "International Business Machines",
        "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        "CIK": "51143",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "TECHNOLOGY",
        "Industry": "COMPUTER & OFFICE EQUIPMENT",
        "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
        "FiscalYearEnd": "December",
        "LatestQuarter": "2024-03-31",
        "MarketCapitalization": "156943335000",
        "EBITDA": "14380000000",
        "PERatio": "19.37",
        "PEGRatio": "4.2",
        "BookValue": "25.32",
        "DividendPerShare": "6.64",
        "DividendYield": "0.0391",
        "EPS": "8.82",
        "RevenuePerShareTTM": "67.94",
        "ProfitMargin": "0.132",
        "OperatingMarginTTM": "0.102",
        "ReturnOnAssetsTTM": "0.0458",
        "ReturnOnEquityTTM": "0.362",
        "RevenueTTM": "62068998000",
        "GrossProfitTTM": "32688000000",
        "DilutedEPSTTM": "8.82",
        "QuarterlyEarningsGrowthYOY": "0.701",
        "QuarterlyRevenueGrowthYOY": "0.015",
        "AnalystTargetPrice": "181.05",
        "AnalystRatingStrongBuy": "4",
        "AnalystRatingBuy": "5",
        "AnalystRatingHold": "9",
        "AnalystRatingSell": "3",
        "AnalystRatingStrongSell": "0",
        "TrailingPE": "19.37",
        "ForwardPE": "18.12",
        "PriceToSalesRatioTTM": "2.701",
        "PriceToBookRatio": "7.42",
        "EVToRevenue": "3.453",
        "EVToEBITDA": "14.54",
        "Beta": "0.718",
        "52WeekHigh": "197.22",
        "52WeekLow": "126.18",
        "50DayMovingAverage": "170.57",
        "200DayMovingAverage": "167.29",
        "SharesOutstanding": "918603000",
        "DividendDate": "2024-06-10",
        "ExDividendDate": "2024-05-09"
    }
    const tempChartData = {
        labels: ["January", "February", "March", "April", "May", "June"],
        // labels: tempKey,
        datasets: [
          {
            data: [1,3,2,6,3,5],
            // data: closingVals,
            color: (opacity = 1) => `rgba(134, 65, 244, ${opacity})`, 
            strokeWidth: 2 
          }
        ],
        // legend: ["Rainy Days"] 
      };
    
    const uri = `https://picsum.photos/200`
    const screenWidth = Dimensions.get('window').width

    
    // const tempKey = Object.keys(timeSeries)
    // const checkValues = ()=>{
        //     try{
            //         let tempVals = []
            //         console.log("tempKey.length",tempKey[0].split(" ")[1]);
    //         let stockKeys = []
    //         tempKey.forEach((ele)=>{
    //             stockKeys.push(ele.split(" ")[1]);
    //         })
    //         // setStockDates(tempKey)
    //         setStockDates(stockKeys)

    //         tempKey.forEach(key => {

    //             // console.log(`Timestamp: ${key}`);
    //             // console.log(`1. open: ${timeSeries[key]["1. open"]}`);
    //             // console.log(`2. high: ${timeSeries[key]["2. high"]}`);
    //             // console.log(`3. low: ${timeSeries[key]["3. low"]}`);
    //             // console.log(`5. volume: ${timeSeries[key]["5. volume"]}`);
    //             // console.log('');

    //             // console.log(`4. close: ${timeSeries[key]["4. close"]}`);
    //             const closeVal = timeSeries[key]["4. close"]
    //             tempVals.push(closeVal)
    //         });
    //         setClosingVals(tempVals)
    //     }catch(e){
    //         console.error("Error checkValues", e);
    //     }
    // }

    const getSampleData = async ()=>{
        try{
            const timeSeries = TimeSeries5min[`Time Series (5min)`]
            const outputData = {}
            
            for (const timestamp in timeSeries) {
                const k = Number(moment(timestamp).format('X'))
                console.log(typeof(k), k);
                outputData[k] = {
                    "4. close": Number(timeSeries[timestamp]["4. close"])
                };
            }
            const finalData = Object.entries(outputData).map(([x, { "4. close": y }]) => ({ x : Number(x), y }))
            console.log("finalData",finalData);
            // setSampleData(outputData)
            fetchSampleData().then((data)=>{
                setSampleData(data)
            })
            fetchLabelData().then((data) => {
                setLabels(data);
              });
              fetchStockData().then((data)=>{
                setStockClose(data)
              })

              function fetchSampleData() {
                return new Promise((resolve) => {
                  setTimeout(() => {
                    resolve(Object.entries(outputData).map(([x, { "4. close": y }]) => ({ x : Number(x), y })));
                  }, 1000);
                });
              }
            function fetchLabelData() {
                return new Promise((resolve) => {
                  setTimeout(() => {
                    resolve(Object.keys(outputData).reverse());
                  }, 2000);
                });
              }
              function fetchStockData() {
                return new Promise((resolve) => {
                  setTimeout(() => {
                    resolve(labels?.map(label => parseFloat(outputData[label]["4. close"])));
                  }, 2000);
                });
              }
            // setStockClose(labels?.map(label => parseFloat(outputData[label]["4. close"])))

            // console.log("Labels : ", labels);
        }
        catch(e){
            console.error("Error getSampleData", e);
        }
    }
    
    const [stock, setStock] = useState({})


    useEffect(()=>{
        setLoading(true)
        setStock(data)
        // setChartData(tempChartData)
        // checkValues()
        getSampleData()

        setTimeout(()=>setLoading(false),2000)
    },[])

    useEffect(()=>{
        // console.log("stockDates ", stockDates);
        // console.log("closingVals ", closingVals);
        // if(stockDates.length > 0 && closingVals.length>0){
            const tempChartData = {
                labels: stockDates,
                // labels: tempKey,
                datasets: [
                  {
                    data: closingVals,
                    // data: closingVals,
                    color: (opacity = 1) => `rgba(134, 65, 244, ${opacity})`, 
                    strokeWidth: 2 
                  }
                ],
                // legend: ["Rainy Days"] 
              };
              setChartData(tempChartData)
                // console.log("chartData",chartData);

        // }


    },[stockDates, closingVals])

    const stockParams = [
        { id: 1, name: "Market Cap", value: `$${(stock?.MarketCapitalization/1e10).toFixed(2)}T`},
        { id: 2, name: "P/E Ratio", value: stock?.PERatio},
        { id: 3, name: "Beta", value: stock?.Beta},
        { id: 4, name: "Dividend Yield", value: stock?.DividendYield+"%"},
        { id: 5, name: "Profit Margin", value: stock?.ProfitMargin},
    ]

    
    const chartConfig = {
        backgroundGradientFrom: "#FFFFFF",
        // backgroundGradientFromOpacity: 0,
        backgroundGradientTo: "#FFFFFF",
        // backgroundGradientToOpacity: 0.5,
        color: (opacity = 1) => `rgba(26, 255, 146, ${opacity})`,
        strokeWidth: 2,
        barPercentage: 0.5,
        useShadowColorFromDataset: false 
    };


    

    
        return (
            loading ? <Loader/> :
            <ScrollView style={{backgroundColor: "#FFFFFF"}}>
                <TitleBar navigation={navigation} screen="Details"/>
    
                <View style={{flexDirection: "row", justifyContent: "space-between", paddingRight: 10}}>
                    <View style={{flexDirection: "row"}}>
                        <Image source={{uri : uri}} style={styles.image}/>
                        <View>
                            <Text style={{color: "black"}}>{stock?.Name}</Text>
                            <View style={{flexDirection: "row"}}>
                                <Text style={{color: "black"}}>{stock?.Symbol}, </Text>
                                <Text style={{color: "black"}}>{stock?.AssetType}</Text>
                            </View>
                            <Text style={{color: "black"}}>{stock?.Exchange}</Text>
                        </View>
                    </View>
                    <View>
                        <Text style={{color: "black"}}> {route?.params?.item?.price}</Text>
                        <Text style={{color: "black"}}>  {route?.params?.item?.change_percentage}</Text>
                    </View>
    
                </View>
                
                {/* 
                    <View style={{marginVertical: 10, justifyContent: "center", alignItems: "center"}}>
                        <LineChart
                            // data={ tempChartData}
                            data={ chartData}
                            width={screenWidth}
                            height={220}
                            withDots={false}
                            xLabelsOffset={10}
                            chartConfig={chartConfig}
                        />

                    </View> 
                */}
                <View style={styles.container}>
                    {
                        labels.length > 0 &&
                        <Chart sampleData={sampleData} labels={labels} stockClose={stockClose} />
                        // <LineChart
                        //     data={{
                        //         labels:  ["A","V", "W"],
                        //         datasets: [
                        //             {
                        //                 data: ["150", "240", "210"],
                        //             },

                        //         ],
                        //     }}
                        //     width={Dimensions.get('window').width} // from react-native
                        //     height={220}
                        //     yAxisLabel="$"
                        //     yAxisSuffix="k"
                        //     yAxisInterval={1} // optional, defaults to 1
                        //     chartConfig={{
                        //         backgroundColor: '#e26a00',
                        //         backgroundGradientFrom: '#fb8c00',
                        //         backgroundGradientTo: '#ffa726',
                        //         decimalPlaces: 2, // optional, defaults to 2dp
                        //         color: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
                        //         labelColor: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
                        //         style: {
                        //         borderRadius: 16,
                        //         },
                        //         propsForDots: {
                        //         r: '6',
                        //         strokeWidth: '2',
                        //         stroke: '#ffa726',
                        //         },
                        //     }}
                        //     bezier
                        //     style={{
                        //         marginVertical: 8,
                        //         borderRadius: 16,
                        //     }}
                        // />
                    }
                </View>
    
                <StockDesc stock={stock} stockParams={stockParams} />
            </ScrollView>
        )
       
    // }catch(e){
    //     return(
    //         navigation.navigate("Error")
    //     )
    // }
}

export default Details

const styles = StyleSheet.create({
    image: {
        width: 60,
        height: 60,
        borderColor: 'lightgray',
        borderWidth: 2,
        borderRadius: 30,
        marginHorizontal: 6
      },
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#fff',
      }
})